// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using schedule_api.Services;

#nullable disable

namespace schedule_api.Migrations
{
    [DbContext(typeof(TransitInfoContext))]
    partial class TransitInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("schedule_api.Entities.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("End")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Frequency")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScheduleDay")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Start")
                        .HasColumnType("TEXT");

                    b.Property<int>("TopLevelRouteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RouteId");

                    b.HasIndex("TopLevelRouteId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            RouteId = 1,
                            End = new TimeSpan(0, 23, 0, 0, 0),
                            Frequency = new TimeSpan(0, 0, 10, 0, 0),
                            ScheduleDay = 0,
                            Start = new TimeSpan(0, 6, 0, 0, 0),
                            TopLevelRouteId = 1
                        },
                        new
                        {
                            RouteId = 2,
                            End = new TimeSpan(0, 23, 0, 0, 0),
                            Frequency = new TimeSpan(0, 0, 15, 0, 0),
                            ScheduleDay = 1,
                            Start = new TimeSpan(0, 9, 0, 0, 0),
                            TopLevelRouteId = 1
                        },
                        new
                        {
                            RouteId = 3,
                            End = new TimeSpan(0, 23, 0, 0, 0),
                            Frequency = new TimeSpan(0, 0, 15, 0, 0),
                            ScheduleDay = 2,
                            Start = new TimeSpan(0, 9, 0, 0, 0),
                            TopLevelRouteId = 1
                        },
                        new
                        {
                            RouteId = 4,
                            End = new TimeSpan(0, 23, 0, 0, 0),
                            Frequency = new TimeSpan(0, 0, 10, 0, 0),
                            ScheduleDay = 0,
                            Start = new TimeSpan(0, 6, 0, 0, 0),
                            TopLevelRouteId = 2
                        },
                        new
                        {
                            RouteId = 5,
                            End = new TimeSpan(0, 23, 0, 0, 0),
                            Frequency = new TimeSpan(0, 0, 15, 0, 0),
                            ScheduleDay = 1,
                            Start = new TimeSpan(0, 9, 0, 0, 0),
                            TopLevelRouteId = 2
                        },
                        new
                        {
                            RouteId = 6,
                            End = new TimeSpan(0, 23, 0, 0, 0),
                            Frequency = new TimeSpan(0, 0, 15, 0, 0),
                            ScheduleDay = 2,
                            Start = new TimeSpan(0, 9, 0, 0, 0),
                            TopLevelRouteId = 2
                        });
                });

            modelBuilder.Entity("schedule_api.Entities.Schedule", b =>
                {
                    b.Property<int>("RouteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StopId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("ScheduleOffset")
                        .HasColumnType("TEXT");

                    b.HasKey("RouteId", "StopId");

                    b.HasIndex("StopId");

                    b.ToTable("RouteSchedules");

                    b.HasData(
                        new
                        {
                            RouteId = 1,
                            StopId = 1,
                            ScheduleOffset = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            RouteId = 1,
                            StopId = 2,
                            ScheduleOffset = new TimeSpan(0, 0, 3, 0, 0)
                        },
                        new
                        {
                            RouteId = 1,
                            StopId = 3,
                            ScheduleOffset = new TimeSpan(0, 0, 6, 0, 0)
                        },
                        new
                        {
                            RouteId = 1,
                            StopId = 4,
                            ScheduleOffset = new TimeSpan(0, 0, 9, 0, 0)
                        },
                        new
                        {
                            RouteId = 1,
                            StopId = 5,
                            ScheduleOffset = new TimeSpan(0, 0, 12, 0, 0)
                        },
                        new
                        {
                            RouteId = 1,
                            StopId = 6,
                            ScheduleOffset = new TimeSpan(0, 0, 15, 0, 0)
                        },
                        new
                        {
                            RouteId = 1,
                            StopId = 7,
                            ScheduleOffset = new TimeSpan(0, 0, 18, 0, 0)
                        },
                        new
                        {
                            RouteId = 1,
                            StopId = 8,
                            ScheduleOffset = new TimeSpan(0, 0, 21, 0, 0)
                        },
                        new
                        {
                            RouteId = 1,
                            StopId = 9,
                            ScheduleOffset = new TimeSpan(0, 0, 24, 0, 0)
                        },
                        new
                        {
                            RouteId = 1,
                            StopId = 10,
                            ScheduleOffset = new TimeSpan(0, 0, 27, 0, 0)
                        },
                        new
                        {
                            RouteId = 1,
                            StopId = 11,
                            ScheduleOffset = new TimeSpan(0, 0, 30, 0, 0)
                        },
                        new
                        {
                            RouteId = 1,
                            StopId = 12,
                            ScheduleOffset = new TimeSpan(0, 0, 33, 0, 0)
                        },
                        new
                        {
                            RouteId = 1,
                            StopId = 13,
                            ScheduleOffset = new TimeSpan(0, 0, 36, 0, 0)
                        },
                        new
                        {
                            RouteId = 1,
                            StopId = 14,
                            ScheduleOffset = new TimeSpan(0, 0, 39, 0, 0)
                        },
                        new
                        {
                            RouteId = 1,
                            StopId = 15,
                            ScheduleOffset = new TimeSpan(0, 0, 42, 0, 0)
                        },
                        new
                        {
                            RouteId = 1,
                            StopId = 16,
                            ScheduleOffset = new TimeSpan(0, 0, 45, 0, 0)
                        },
                        new
                        {
                            RouteId = 1,
                            StopId = 17,
                            ScheduleOffset = new TimeSpan(0, 0, 48, 0, 0)
                        },
                        new
                        {
                            RouteId = 1,
                            StopId = 18,
                            ScheduleOffset = new TimeSpan(0, 0, 51, 0, 0)
                        },
                        new
                        {
                            RouteId = 2,
                            StopId = 1,
                            ScheduleOffset = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            RouteId = 2,
                            StopId = 2,
                            ScheduleOffset = new TimeSpan(0, 0, 3, 0, 0)
                        },
                        new
                        {
                            RouteId = 2,
                            StopId = 3,
                            ScheduleOffset = new TimeSpan(0, 0, 6, 0, 0)
                        },
                        new
                        {
                            RouteId = 2,
                            StopId = 4,
                            ScheduleOffset = new TimeSpan(0, 0, 9, 0, 0)
                        },
                        new
                        {
                            RouteId = 2,
                            StopId = 5,
                            ScheduleOffset = new TimeSpan(0, 0, 12, 0, 0)
                        },
                        new
                        {
                            RouteId = 2,
                            StopId = 6,
                            ScheduleOffset = new TimeSpan(0, 0, 15, 0, 0)
                        },
                        new
                        {
                            RouteId = 2,
                            StopId = 7,
                            ScheduleOffset = new TimeSpan(0, 0, 18, 0, 0)
                        },
                        new
                        {
                            RouteId = 2,
                            StopId = 8,
                            ScheduleOffset = new TimeSpan(0, 0, 21, 0, 0)
                        },
                        new
                        {
                            RouteId = 2,
                            StopId = 9,
                            ScheduleOffset = new TimeSpan(0, 0, 24, 0, 0)
                        },
                        new
                        {
                            RouteId = 2,
                            StopId = 10,
                            ScheduleOffset = new TimeSpan(0, 0, 27, 0, 0)
                        },
                        new
                        {
                            RouteId = 2,
                            StopId = 11,
                            ScheduleOffset = new TimeSpan(0, 0, 30, 0, 0)
                        },
                        new
                        {
                            RouteId = 2,
                            StopId = 12,
                            ScheduleOffset = new TimeSpan(0, 0, 33, 0, 0)
                        },
                        new
                        {
                            RouteId = 2,
                            StopId = 13,
                            ScheduleOffset = new TimeSpan(0, 0, 36, 0, 0)
                        },
                        new
                        {
                            RouteId = 2,
                            StopId = 14,
                            ScheduleOffset = new TimeSpan(0, 0, 39, 0, 0)
                        },
                        new
                        {
                            RouteId = 2,
                            StopId = 15,
                            ScheduleOffset = new TimeSpan(0, 0, 42, 0, 0)
                        },
                        new
                        {
                            RouteId = 2,
                            StopId = 16,
                            ScheduleOffset = new TimeSpan(0, 0, 45, 0, 0)
                        },
                        new
                        {
                            RouteId = 2,
                            StopId = 17,
                            ScheduleOffset = new TimeSpan(0, 0, 48, 0, 0)
                        },
                        new
                        {
                            RouteId = 2,
                            StopId = 18,
                            ScheduleOffset = new TimeSpan(0, 0, 51, 0, 0)
                        },
                        new
                        {
                            RouteId = 3,
                            StopId = 1,
                            ScheduleOffset = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            RouteId = 3,
                            StopId = 2,
                            ScheduleOffset = new TimeSpan(0, 0, 3, 0, 0)
                        },
                        new
                        {
                            RouteId = 3,
                            StopId = 3,
                            ScheduleOffset = new TimeSpan(0, 0, 6, 0, 0)
                        },
                        new
                        {
                            RouteId = 3,
                            StopId = 4,
                            ScheduleOffset = new TimeSpan(0, 0, 9, 0, 0)
                        },
                        new
                        {
                            RouteId = 3,
                            StopId = 5,
                            ScheduleOffset = new TimeSpan(0, 0, 12, 0, 0)
                        },
                        new
                        {
                            RouteId = 3,
                            StopId = 6,
                            ScheduleOffset = new TimeSpan(0, 0, 15, 0, 0)
                        },
                        new
                        {
                            RouteId = 3,
                            StopId = 7,
                            ScheduleOffset = new TimeSpan(0, 0, 18, 0, 0)
                        },
                        new
                        {
                            RouteId = 3,
                            StopId = 8,
                            ScheduleOffset = new TimeSpan(0, 0, 21, 0, 0)
                        },
                        new
                        {
                            RouteId = 3,
                            StopId = 9,
                            ScheduleOffset = new TimeSpan(0, 0, 24, 0, 0)
                        },
                        new
                        {
                            RouteId = 3,
                            StopId = 10,
                            ScheduleOffset = new TimeSpan(0, 0, 27, 0, 0)
                        },
                        new
                        {
                            RouteId = 3,
                            StopId = 11,
                            ScheduleOffset = new TimeSpan(0, 0, 30, 0, 0)
                        },
                        new
                        {
                            RouteId = 3,
                            StopId = 12,
                            ScheduleOffset = new TimeSpan(0, 0, 33, 0, 0)
                        },
                        new
                        {
                            RouteId = 3,
                            StopId = 13,
                            ScheduleOffset = new TimeSpan(0, 0, 36, 0, 0)
                        },
                        new
                        {
                            RouteId = 3,
                            StopId = 14,
                            ScheduleOffset = new TimeSpan(0, 0, 39, 0, 0)
                        },
                        new
                        {
                            RouteId = 3,
                            StopId = 15,
                            ScheduleOffset = new TimeSpan(0, 0, 42, 0, 0)
                        },
                        new
                        {
                            RouteId = 3,
                            StopId = 16,
                            ScheduleOffset = new TimeSpan(0, 0, 45, 0, 0)
                        },
                        new
                        {
                            RouteId = 3,
                            StopId = 17,
                            ScheduleOffset = new TimeSpan(0, 0, 48, 0, 0)
                        },
                        new
                        {
                            RouteId = 3,
                            StopId = 18,
                            ScheduleOffset = new TimeSpan(0, 0, 51, 0, 0)
                        },
                        new
                        {
                            RouteId = 4,
                            StopId = 18,
                            ScheduleOffset = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            RouteId = 4,
                            StopId = 17,
                            ScheduleOffset = new TimeSpan(0, 0, 3, 0, 0)
                        },
                        new
                        {
                            RouteId = 4,
                            StopId = 16,
                            ScheduleOffset = new TimeSpan(0, 0, 6, 0, 0)
                        },
                        new
                        {
                            RouteId = 4,
                            StopId = 15,
                            ScheduleOffset = new TimeSpan(0, 0, 9, 0, 0)
                        },
                        new
                        {
                            RouteId = 4,
                            StopId = 14,
                            ScheduleOffset = new TimeSpan(0, 0, 12, 0, 0)
                        },
                        new
                        {
                            RouteId = 4,
                            StopId = 13,
                            ScheduleOffset = new TimeSpan(0, 0, 15, 0, 0)
                        },
                        new
                        {
                            RouteId = 4,
                            StopId = 12,
                            ScheduleOffset = new TimeSpan(0, 0, 18, 0, 0)
                        },
                        new
                        {
                            RouteId = 4,
                            StopId = 11,
                            ScheduleOffset = new TimeSpan(0, 0, 21, 0, 0)
                        },
                        new
                        {
                            RouteId = 4,
                            StopId = 10,
                            ScheduleOffset = new TimeSpan(0, 0, 24, 0, 0)
                        },
                        new
                        {
                            RouteId = 4,
                            StopId = 9,
                            ScheduleOffset = new TimeSpan(0, 0, 27, 0, 0)
                        },
                        new
                        {
                            RouteId = 4,
                            StopId = 8,
                            ScheduleOffset = new TimeSpan(0, 0, 30, 0, 0)
                        },
                        new
                        {
                            RouteId = 4,
                            StopId = 7,
                            ScheduleOffset = new TimeSpan(0, 0, 33, 0, 0)
                        },
                        new
                        {
                            RouteId = 4,
                            StopId = 6,
                            ScheduleOffset = new TimeSpan(0, 0, 36, 0, 0)
                        },
                        new
                        {
                            RouteId = 4,
                            StopId = 5,
                            ScheduleOffset = new TimeSpan(0, 0, 39, 0, 0)
                        },
                        new
                        {
                            RouteId = 4,
                            StopId = 4,
                            ScheduleOffset = new TimeSpan(0, 0, 42, 0, 0)
                        },
                        new
                        {
                            RouteId = 4,
                            StopId = 3,
                            ScheduleOffset = new TimeSpan(0, 0, 45, 0, 0)
                        },
                        new
                        {
                            RouteId = 4,
                            StopId = 2,
                            ScheduleOffset = new TimeSpan(0, 0, 48, 0, 0)
                        },
                        new
                        {
                            RouteId = 4,
                            StopId = 1,
                            ScheduleOffset = new TimeSpan(0, 0, 51, 0, 0)
                        },
                        new
                        {
                            RouteId = 5,
                            StopId = 18,
                            ScheduleOffset = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            RouteId = 5,
                            StopId = 17,
                            ScheduleOffset = new TimeSpan(0, 0, 3, 0, 0)
                        },
                        new
                        {
                            RouteId = 5,
                            StopId = 16,
                            ScheduleOffset = new TimeSpan(0, 0, 6, 0, 0)
                        },
                        new
                        {
                            RouteId = 5,
                            StopId = 15,
                            ScheduleOffset = new TimeSpan(0, 0, 9, 0, 0)
                        },
                        new
                        {
                            RouteId = 5,
                            StopId = 14,
                            ScheduleOffset = new TimeSpan(0, 0, 12, 0, 0)
                        },
                        new
                        {
                            RouteId = 5,
                            StopId = 13,
                            ScheduleOffset = new TimeSpan(0, 0, 15, 0, 0)
                        },
                        new
                        {
                            RouteId = 5,
                            StopId = 12,
                            ScheduleOffset = new TimeSpan(0, 0, 18, 0, 0)
                        },
                        new
                        {
                            RouteId = 5,
                            StopId = 11,
                            ScheduleOffset = new TimeSpan(0, 0, 21, 0, 0)
                        },
                        new
                        {
                            RouteId = 5,
                            StopId = 10,
                            ScheduleOffset = new TimeSpan(0, 0, 24, 0, 0)
                        },
                        new
                        {
                            RouteId = 5,
                            StopId = 9,
                            ScheduleOffset = new TimeSpan(0, 0, 27, 0, 0)
                        },
                        new
                        {
                            RouteId = 5,
                            StopId = 8,
                            ScheduleOffset = new TimeSpan(0, 0, 30, 0, 0)
                        },
                        new
                        {
                            RouteId = 5,
                            StopId = 7,
                            ScheduleOffset = new TimeSpan(0, 0, 33, 0, 0)
                        },
                        new
                        {
                            RouteId = 5,
                            StopId = 6,
                            ScheduleOffset = new TimeSpan(0, 0, 36, 0, 0)
                        },
                        new
                        {
                            RouteId = 5,
                            StopId = 5,
                            ScheduleOffset = new TimeSpan(0, 0, 39, 0, 0)
                        },
                        new
                        {
                            RouteId = 5,
                            StopId = 4,
                            ScheduleOffset = new TimeSpan(0, 0, 42, 0, 0)
                        },
                        new
                        {
                            RouteId = 5,
                            StopId = 3,
                            ScheduleOffset = new TimeSpan(0, 0, 45, 0, 0)
                        },
                        new
                        {
                            RouteId = 5,
                            StopId = 2,
                            ScheduleOffset = new TimeSpan(0, 0, 48, 0, 0)
                        },
                        new
                        {
                            RouteId = 5,
                            StopId = 1,
                            ScheduleOffset = new TimeSpan(0, 0, 51, 0, 0)
                        },
                        new
                        {
                            RouteId = 6,
                            StopId = 18,
                            ScheduleOffset = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            RouteId = 6,
                            StopId = 17,
                            ScheduleOffset = new TimeSpan(0, 0, 3, 0, 0)
                        },
                        new
                        {
                            RouteId = 6,
                            StopId = 16,
                            ScheduleOffset = new TimeSpan(0, 0, 6, 0, 0)
                        },
                        new
                        {
                            RouteId = 6,
                            StopId = 15,
                            ScheduleOffset = new TimeSpan(0, 0, 9, 0, 0)
                        },
                        new
                        {
                            RouteId = 6,
                            StopId = 14,
                            ScheduleOffset = new TimeSpan(0, 0, 12, 0, 0)
                        },
                        new
                        {
                            RouteId = 6,
                            StopId = 13,
                            ScheduleOffset = new TimeSpan(0, 0, 15, 0, 0)
                        },
                        new
                        {
                            RouteId = 6,
                            StopId = 12,
                            ScheduleOffset = new TimeSpan(0, 0, 18, 0, 0)
                        },
                        new
                        {
                            RouteId = 6,
                            StopId = 11,
                            ScheduleOffset = new TimeSpan(0, 0, 21, 0, 0)
                        },
                        new
                        {
                            RouteId = 6,
                            StopId = 10,
                            ScheduleOffset = new TimeSpan(0, 0, 24, 0, 0)
                        },
                        new
                        {
                            RouteId = 6,
                            StopId = 9,
                            ScheduleOffset = new TimeSpan(0, 0, 27, 0, 0)
                        },
                        new
                        {
                            RouteId = 6,
                            StopId = 8,
                            ScheduleOffset = new TimeSpan(0, 0, 30, 0, 0)
                        },
                        new
                        {
                            RouteId = 6,
                            StopId = 7,
                            ScheduleOffset = new TimeSpan(0, 0, 33, 0, 0)
                        },
                        new
                        {
                            RouteId = 6,
                            StopId = 6,
                            ScheduleOffset = new TimeSpan(0, 0, 36, 0, 0)
                        },
                        new
                        {
                            RouteId = 6,
                            StopId = 5,
                            ScheduleOffset = new TimeSpan(0, 0, 39, 0, 0)
                        },
                        new
                        {
                            RouteId = 6,
                            StopId = 4,
                            ScheduleOffset = new TimeSpan(0, 0, 42, 0, 0)
                        },
                        new
                        {
                            RouteId = 6,
                            StopId = 3,
                            ScheduleOffset = new TimeSpan(0, 0, 45, 0, 0)
                        },
                        new
                        {
                            RouteId = 6,
                            StopId = 2,
                            ScheduleOffset = new TimeSpan(0, 0, 48, 0, 0)
                        },
                        new
                        {
                            RouteId = 6,
                            StopId = 1,
                            ScheduleOffset = new TimeSpan(0, 0, 51, 0, 0)
                        });
                });

            modelBuilder.Entity("schedule_api.Entities.Stop", b =>
                {
                    b.Property<int>("StopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("StopId");

                    b.ToTable("Stops");

                    b.HasData(
                        new
                        {
                            StopId = 1,
                            Address = "Beaudry Ave & 3rd St"
                        },
                        new
                        {
                            StopId = 2,
                            Address = "4th St & Figueroa St"
                        },
                        new
                        {
                            StopId = 3,
                            Address = "Flower St & 5th St"
                        },
                        new
                        {
                            StopId = 4,
                            Address = "Flower St & 7th St"
                        },
                        new
                        {
                            StopId = 5,
                            Address = "Flower St & 8th St"
                        },
                        new
                        {
                            StopId = 6,
                            Address = "Flower St & 9th St"
                        },
                        new
                        {
                            StopId = 7,
                            Address = "Flower St & Olympic Blvd"
                        },
                        new
                        {
                            StopId = 8,
                            Address = "Figueroa & 12th St (Crypto.com Arena)"
                        },
                        new
                        {
                            StopId = 9,
                            Address = "Figueroa St & Pico Blvd"
                        },
                        new
                        {
                            StopId = 10,
                            Address = "Figueroa St & Venice Blvd"
                        },
                        new
                        {
                            StopId = 11,
                            Address = "Figueroa St & Washington Blvd"
                        },
                        new
                        {
                            StopId = 12,
                            Address = "Figueroa St & 23rd St"
                        },
                        new
                        {
                            StopId = 13,
                            Address = "Figueroa St & Adams Blvd"
                        },
                        new
                        {
                            StopId = 14,
                            Address = "Figueroa St & 30th St"
                        },
                        new
                        {
                            StopId = 15,
                            Address = "Figueroa St & Jefferson Blvd"
                        },
                        new
                        {
                            StopId = 16,
                            Address = "Figueroa St & McCarthy Way"
                        },
                        new
                        {
                            StopId = 17,
                            Address = "Exposition Blvd & Trousdale Pkwy"
                        },
                        new
                        {
                            StopId = 18,
                            Address = "Exposition Blvd & Watt Way"
                        });
                });

            modelBuilder.Entity("schedule_api.Entities.TopLevelRoute", b =>
                {
                    b.Property<int>("TopLevelRouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TopLevelRouteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("TopLevelRouteId");

                    b.ToTable("TopLevelRoutes");

                    b.HasData(
                        new
                        {
                            TopLevelRouteId = 1,
                            TopLevelRouteName = "DASH Downtown F Northbound"
                        },
                        new
                        {
                            TopLevelRouteId = 2,
                            TopLevelRouteName = "DASH Downtown F Southbound"
                        });
                });

            modelBuilder.Entity("schedule_api.Entities.Route", b =>
                {
                    b.HasOne("schedule_api.Entities.TopLevelRoute", "TopLevelRoute")
                        .WithMany("ChildRoutes")
                        .HasForeignKey("TopLevelRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TopLevelRoute");
                });

            modelBuilder.Entity("schedule_api.Entities.Schedule", b =>
                {
                    b.HasOne("schedule_api.Entities.Route", "Route")
                        .WithMany("RouteSchedule")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("schedule_api.Entities.Stop", "Stop")
                        .WithMany("RouteSchedule")
                        .HasForeignKey("StopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("Stop");
                });

            modelBuilder.Entity("schedule_api.Entities.Route", b =>
                {
                    b.Navigation("RouteSchedule");
                });

            modelBuilder.Entity("schedule_api.Entities.Stop", b =>
                {
                    b.Navigation("RouteSchedule");
                });

            modelBuilder.Entity("schedule_api.Entities.TopLevelRoute", b =>
                {
                    b.Navigation("ChildRoutes");
                });
#pragma warning restore 612, 618
        }
    }
}
