// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using schedule_api.Services;

#nullable disable

namespace schedule_api.Migrations
{
    [DbContext(typeof(TransitInfoContext))]
    partial class TransitInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("schedule_api.Entities.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("End")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Frequency")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScheduleDay")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Start")
                        .HasColumnType("TEXT");

                    b.Property<int>("TopLevelRouteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RouteId");

                    b.HasIndex("TopLevelRouteId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            RouteId = 1,
                            End = new TimeSpan(0, 23, 0, 0, 0),
                            Frequency = new TimeSpan(0, 0, 10, 0, 0),
                            ScheduleDay = 0,
                            Start = new TimeSpan(0, 6, 0, 0, 0),
                            TopLevelRouteId = 1
                        },
                        new
                        {
                            RouteId = 2,
                            End = new TimeSpan(0, 23, 0, 0, 0),
                            Frequency = new TimeSpan(0, 0, 15, 0, 0),
                            ScheduleDay = 1,
                            Start = new TimeSpan(0, 9, 0, 0, 0),
                            TopLevelRouteId = 1
                        },
                        new
                        {
                            RouteId = 3,
                            End = new TimeSpan(0, 23, 0, 0, 0),
                            Frequency = new TimeSpan(0, 0, 15, 0, 0),
                            ScheduleDay = 2,
                            Start = new TimeSpan(0, 9, 0, 0, 0),
                            TopLevelRouteId = 1
                        },
                        new
                        {
                            RouteId = 4,
                            End = new TimeSpan(0, 23, 0, 0, 0),
                            Frequency = new TimeSpan(0, 0, 10, 0, 0),
                            ScheduleDay = 0,
                            Start = new TimeSpan(0, 6, 0, 0, 0),
                            TopLevelRouteId = 2
                        },
                        new
                        {
                            RouteId = 5,
                            End = new TimeSpan(0, 23, 0, 0, 0),
                            Frequency = new TimeSpan(0, 0, 15, 0, 0),
                            ScheduleDay = 1,
                            Start = new TimeSpan(0, 9, 0, 0, 0),
                            TopLevelRouteId = 2
                        },
                        new
                        {
                            RouteId = 6,
                            End = new TimeSpan(0, 23, 0, 0, 0),
                            Frequency = new TimeSpan(0, 0, 15, 0, 0),
                            ScheduleDay = 2,
                            Start = new TimeSpan(0, 9, 0, 0, 0),
                            TopLevelRouteId = 2
                        });
                });

            modelBuilder.Entity("schedule_api.Entities.Schedule", b =>
                {
                    b.Property<int>("RouteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StopId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("ScheduleOffset")
                        .HasColumnType("TEXT");

                    b.HasKey("RouteId", "StopId");

                    b.HasIndex("StopId");

                    b.ToTable("Schedule");

                    b.HasData(
                        new
                        {
                            RouteId = 1,
                            StopId = 1,
                            ScheduleOffset = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            RouteId = 1,
                            StopId = 2,
                            ScheduleOffset = new TimeSpan(0, 0, 5, 0, 0)
                        },
                        new
                        {
                            RouteId = 1,
                            StopId = 3,
                            ScheduleOffset = new TimeSpan(0, 0, 10, 0, 0)
                        },
                        new
                        {
                            RouteId = 1,
                            StopId = 4,
                            ScheduleOffset = new TimeSpan(0, 0, 15, 0, 0)
                        },
                        new
                        {
                            RouteId = 1,
                            StopId = 5,
                            ScheduleOffset = new TimeSpan(0, 0, 20, 0, 0)
                        },
                        new
                        {
                            RouteId = 2,
                            StopId = 1,
                            ScheduleOffset = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            RouteId = 2,
                            StopId = 2,
                            ScheduleOffset = new TimeSpan(0, 0, 5, 0, 0)
                        },
                        new
                        {
                            RouteId = 2,
                            StopId = 3,
                            ScheduleOffset = new TimeSpan(0, 0, 10, 0, 0)
                        },
                        new
                        {
                            RouteId = 2,
                            StopId = 4,
                            ScheduleOffset = new TimeSpan(0, 0, 15, 0, 0)
                        },
                        new
                        {
                            RouteId = 2,
                            StopId = 5,
                            ScheduleOffset = new TimeSpan(0, 0, 20, 0, 0)
                        },
                        new
                        {
                            RouteId = 3,
                            StopId = 1,
                            ScheduleOffset = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            RouteId = 3,
                            StopId = 2,
                            ScheduleOffset = new TimeSpan(0, 0, 5, 0, 0)
                        },
                        new
                        {
                            RouteId = 3,
                            StopId = 3,
                            ScheduleOffset = new TimeSpan(0, 0, 10, 0, 0)
                        },
                        new
                        {
                            RouteId = 3,
                            StopId = 4,
                            ScheduleOffset = new TimeSpan(0, 0, 15, 0, 0)
                        },
                        new
                        {
                            RouteId = 3,
                            StopId = 5,
                            ScheduleOffset = new TimeSpan(0, 0, 20, 0, 0)
                        },
                        new
                        {
                            RouteId = 4,
                            StopId = 5,
                            ScheduleOffset = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            RouteId = 4,
                            StopId = 4,
                            ScheduleOffset = new TimeSpan(0, 0, 5, 0, 0)
                        },
                        new
                        {
                            RouteId = 4,
                            StopId = 3,
                            ScheduleOffset = new TimeSpan(0, 0, 10, 0, 0)
                        },
                        new
                        {
                            RouteId = 4,
                            StopId = 2,
                            ScheduleOffset = new TimeSpan(0, 0, 15, 0, 0)
                        },
                        new
                        {
                            RouteId = 4,
                            StopId = 1,
                            ScheduleOffset = new TimeSpan(0, 0, 20, 0, 0)
                        },
                        new
                        {
                            RouteId = 5,
                            StopId = 5,
                            ScheduleOffset = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            RouteId = 5,
                            StopId = 4,
                            ScheduleOffset = new TimeSpan(0, 0, 5, 0, 0)
                        },
                        new
                        {
                            RouteId = 5,
                            StopId = 3,
                            ScheduleOffset = new TimeSpan(0, 0, 10, 0, 0)
                        },
                        new
                        {
                            RouteId = 5,
                            StopId = 2,
                            ScheduleOffset = new TimeSpan(0, 0, 15, 0, 0)
                        },
                        new
                        {
                            RouteId = 5,
                            StopId = 1,
                            ScheduleOffset = new TimeSpan(0, 0, 20, 0, 0)
                        },
                        new
                        {
                            RouteId = 6,
                            StopId = 5,
                            ScheduleOffset = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            RouteId = 6,
                            StopId = 4,
                            ScheduleOffset = new TimeSpan(0, 0, 5, 0, 0)
                        },
                        new
                        {
                            RouteId = 6,
                            StopId = 3,
                            ScheduleOffset = new TimeSpan(0, 0, 10, 0, 0)
                        },
                        new
                        {
                            RouteId = 6,
                            StopId = 2,
                            ScheduleOffset = new TimeSpan(0, 0, 15, 0, 0)
                        },
                        new
                        {
                            RouteId = 6,
                            StopId = 1,
                            ScheduleOffset = new TimeSpan(0, 0, 20, 0, 0)
                        });
                });

            modelBuilder.Entity("schedule_api.Entities.Stop", b =>
                {
                    b.Property<int>("StopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("StopId");

                    b.ToTable("Stops");

                    b.HasData(
                        new
                        {
                            StopId = 1,
                            Address = "Vermont Ave & Exposition Blvd"
                        },
                        new
                        {
                            StopId = 2,
                            Address = "Vermont Ave & 37th Pl"
                        },
                        new
                        {
                            StopId = 3,
                            Address = "Vermont Ave & 36th Pl"
                        },
                        new
                        {
                            StopId = 4,
                            Address = "Jefferson Blvd & Vermont Ave"
                        },
                        new
                        {
                            StopId = 5,
                            Address = "Jefferson Blvd & McClintock Ave"
                        });
                });

            modelBuilder.Entity("schedule_api.Entities.TopLevelRoute", b =>
                {
                    b.Property<int>("TopLevelRouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TopLevelRouteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("TopLevelRouteId");

                    b.ToTable("TopLevelRoutes");

                    b.HasData(
                        new
                        {
                            TopLevelRouteId = 1,
                            TopLevelRouteName = "DASH Downtown F Northbound"
                        },
                        new
                        {
                            TopLevelRouteId = 2,
                            TopLevelRouteName = "DASH Downtown F Southbound"
                        });
                });

            modelBuilder.Entity("schedule_api.Entities.Route", b =>
                {
                    b.HasOne("schedule_api.Entities.TopLevelRoute", "TopLevelRoute")
                        .WithMany("ChildRoutes")
                        .HasForeignKey("TopLevelRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TopLevelRoute");
                });

            modelBuilder.Entity("schedule_api.Entities.Schedule", b =>
                {
                    b.HasOne("schedule_api.Entities.Route", "Route")
                        .WithMany("RouteSchedule")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("schedule_api.Entities.Stop", "Stop")
                        .WithMany("RouteSchedule")
                        .HasForeignKey("StopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("Stop");
                });

            modelBuilder.Entity("schedule_api.Entities.Route", b =>
                {
                    b.Navigation("RouteSchedule");
                });

            modelBuilder.Entity("schedule_api.Entities.Stop", b =>
                {
                    b.Navigation("RouteSchedule");
                });

            modelBuilder.Entity("schedule_api.Entities.TopLevelRoute", b =>
                {
                    b.Navigation("ChildRoutes");
                });
#pragma warning restore 612, 618
        }
    }
}
